[package]
name = "frank_jwt"
version = "2.4.1"
authors = ["Alex Maslakov <me@gildedhonour.com>, <gilded.honour@gmail.com>"]
license = "Apache-2.0"

homepage = "https://github.com/GildedHonour/frank_jwt"
repository = "https://github.com/GildedHonour/frank_jwt"
documentation = "https://github.com/GildedHonour/frank_jwt"

description = "Implementation of JSON JWT"
keywords = ["jwt", "json", "token", "encryption", "signature"]
readme = "README.md"

[dependencies]
rustc-serialize = "0.3.22"
time = "0.1.36"
openssl = "0.9.7"
