[package]
authors = ["Alex Maslakov <me@gildedhonour.com>, <abc@nothingness.xyz>"]
description = "Implementation of JSON JWT"
documentation = "https://github.com/GildedHonour/frank_jwt"
homepage = "https://github.com/GildedHonour/frank_jwt"
keywords = ["jwt", "json", "token", "encryption", "auth0-jwt"]
license = "Apache-2.0"
name = "frank_jwt"
readme = "README.md"
repository = "https://github.com/GildedHonour/frank_jwt"
version = "3.0.2"

[dependencies]
base64 = "0.9.0"
openssl = "^0.9"
serde = "^1"
serde_json = "^1"
