[package]
name = "frank_jwt"
version = "2.2.0"
authors = ["Alex Maslakov <me@gildedhonour.com>, <gilded.honour@gmail.com>"]
license = "Apache-2.0"

homepage = "https://github.com/GildedHonour/frank_jwt"
repository = "https://github.com/GildedHonour/frank_jwt"
documentation = "https://github.com/GildedHonour/frank_jwt"

description = "Implementation of JSON JWT"
keywords = ["crypto", "jwt", "json", "token", "encryption", "signature", "security"]
readme = "README.md"

[dependencies]
rustc-serialize = "0.3.19"
time = "0.1.26"
openssl = "0.7.14"
